package com.heveamobile.setsandsteps.core.domain

import kotlin.test.Test
import kotlin.test.assertEquals

class UtilsTest {

    @Test
    fun format_step_amount_short() {
        assertEquals(
            "3M",
            formatAmount(
                3_141_593L,
                FormatMode.Short,
            ),
        )
        assertEquals(
            "1K",
            formatAmount(
                1_337,
                FormatMode.Short,
            ),
        )
        assertEquals(
            "1M",
            formatAmount(
                1_000_000L,
                FormatMode.Short,
            ),
        )
        assertEquals(
            "1K",
            formatAmount(
                1_000L,
                FormatMode.Short,
            ),
        )
        assertEquals(
            "0K",
            formatAmount(
                100L,
                FormatMode.Short,
            ),
        )
        assertEquals(
            "0K",
            formatAmount(
                0L,
                FormatMode.Short,
            ),
        )
    }

    @Test
    fun format_step_amount_medium() {
        assertEquals(
            "3,141K",
            formatAmount(
                3_141_593L,
                FormatMode.Medium,
            ),
        )
        assertEquals(
            "1K",
            formatAmount(
                1_337,
                FormatMode.Medium,
            ),
        )
        assertEquals(
            "1,000K",
            formatAmount(
                1_000_000L,
                FormatMode.Medium,
            ),
        )
        assertEquals(
            "1K",
            formatAmount(
                1_000L,
                FormatMode.Medium,
            ),
        )
        assertEquals(
            "100",
            formatAmount(
                100L,
                FormatMode.Medium,
            ),
        )
        assertEquals(
            "0",
            formatAmount(
                0L,
                FormatMode.Medium,
            ),
        )
    }

    @Test
    fun format_step_amount_long() {
        assertEquals(
            "3,141,593",
            formatAmount(
                3_141_593L,
                FormatMode.Long,
            ),
        )
        assertEquals(
            "1,337",
            formatAmount(
                1_337,
                FormatMode.Long,
            ),
        )
        assertEquals(
            "1,000,000",
            formatAmount(
                1_000_000L,
                FormatMode.Long,
            ),
        )
        assertEquals(
            "1,000",
            formatAmount(
                1_000L,
                FormatMode.Long,
            ),
        )
        assertEquals(
            "100",
            formatAmount(
                100L,
                FormatMode.Long,
            ),
        )
        assertEquals(
            "0",
            formatAmount(
                0L,
                FormatMode.Long,
            ),
        )
    }
}